### ISSUE TITLE
Fix Gunicorn Bug

### ISSUE THREAD

**Issue by davidfcalle** [FixIt-App/FixIt-Server#27]

**Comment by davidfcalle** [comment]
[ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/gunicorn/arbiter.py"                                                                                                    , line 578, in spawn_worker
    worker.init_process()
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/gunicorn/workers/bas                                                                                                    e.py", line 126, in init_process
    self.load_wsgi()
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/gunicorn/workers/bas                                                                                                    e.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/gunicorn/app/base.py                                                                                                    ", line 67, in wsgi
    self.callable = self.load()
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp                                                                                                    .py", line 65, in load
    return self.load_wsgiapp()
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp                                                                                                    .py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/gunicorn/util.py", l                                                                                                    ine 352, in import_app
    __import__(module)
  File "/root/FixIt-Server/fixit/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/django/core/wsgi.py"                                                                                                    , line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/django/__init__.py",                                                                                                     line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/django/apps/registry                                                                                                    .py", line 108, in populate
    app_config.import_models(all_models)
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/django/apps/config.p                                                                                                    y", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/root/FixIt-Server/venv/lib/python3.5/importlib/__init__.py", line 126,                                                                                                     in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/django/contrib/auth/                                                                                                    models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/django/contrib/auth/                                                                                                    base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/django/db/models/bas                                                                                                    e.py", line 119, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/django/db/models/bas                                                                                                    e.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/django/db/models/opt                                                                                                    ions.py", line 214, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length(                                                                                                    ))
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/django/db/__init__.p                                                                                                    y", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/django/db/utils.py",                                                                                                     line 211, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/django/db/utils.py",                                                                                                     line 115, in load_backend
    return import_module('%s.base' % backend_name)
  File "/root/FixIt-Server/venv/lib/python3.5/importlib/__init__.py", line 126,                                                                                                     in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/django/db/backends/p                                                                                                    ostgresql/base.py", line 20, in <module>
    import psycopg2 as Database
  File "/root/FixIt-Server/venv/lib/python3.5/site-packages/psycopg2/__init__.py                                                                                                    ", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
SystemError: initialization of _psycopg raised unreported exception

**Comment by davidfcalle** [comment]
Possibly caused by memory leak for running Django in debug mode
